title: MY FIRST BLOG
author: DWIVID
email: tyagdwivid@gmail.com
description: front end web devoloper. # this means to ignore newlines until "baseurl:"
# social links
twitter_username: dDwivid # DO NOT include the @ character, or else the build will fail!
github_username:  dwivid27 # DO NOT include the @ character, or else the build will fail!
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
