title: MY FIRST BLOG
author: DWIVID
email: tyagdwivid@gmail.com
description: > # this means to ignore newlines until "baseurl:"
So you’ve finally decided to start a blog…
You want a life where no one will have the right to tell you what to do, how to do it, and when to do it.
That’s what we all want, right?
# social links
twitter_username: dDwivid # DO NOT include the @ character, or else the build will fail!
github_username:  dwivid27 # DO NOT include the @ character, or else the build will fail!
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
